"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { RefreshCw,Search,Recycle,PackageCheck,Clock3 } from "lucide-react";
import { PackagingPickup } from "@/types/database";
import { useShop } from "@/lib/hooks/use-shop-context";
import { Card } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
interface PickupWithProfile extends PackagingPickup { profiles?: { name?: string; phone?: string } | null }
export default function AdminPickupsPage(){
 const{shopId}=useShop();const[pickups,setPickups]=useState<PickupWithProfile[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[q,setQ]=useState("");
 const load=useCallback(async()=>{if(!shopId)return;setLoading(true);setError("");try{const r=await fetch(`/api/admin/pickups?shop_id=${encodeURIComponent(shopId)}`);const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error?.message||"Không tải được yêu cầu thu gom");setPickups(j.data??[])}catch(e){setError(e instanceof Error?e.message:"Không tải được yêu cầu thu gom")}finally{setLoading(false)}},[shopId]);useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>pickups.filter(p=>`${p.profiles?.name??""} ${p.address} ${p.packaging_type} ${p.status}`.toLowerCase().includes(q.toLowerCase())),[pickups,q]);
 const completed=pickups.filter(p=>p.status==='completed').length;const active=pickups.filter(p=>['pending','assigned','collecting'].includes(p.status)).length;const kg=pickups.reduce((s,p)=>s+Number(p.verified_quantity_kg??p.estimated_quantity_kg??0),0);
 return <div className="space-y-6"><div className="flex flex-col xl:flex-row xl:items-end justify-between gap-4 pb-6 border-b border-slate-200"><div><div className="text-xs uppercase tracking-[.18em] font-semibold text-emerald-600">Reverse Logistics</div><h1 className="mt-2 text-2xl font-bold text-slate-950">Yêu cầu thu gom bao bì</h1><p className="mt-1 text-sm text-slate-500">Theo dõi pickup thật từ khách hàng và trạng thái xử lý theo tuyến.</p></div><button onClick={()=>void load()} className="h-10 px-4 rounded-lg bg-white border border-slate-200 hover:bg-slate-50 text-sm font-semibold text-slate-700 inline-flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/> Làm mới</button></div>
 <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Card><div className="flex justify-between"><div><div className="text-xs uppercase tracking-wider font-semibold text-slate-500">Đang xử lý</div><div className="mt-2 text-3xl font-bold text-slate-950">{active}</div></div><Clock3 className="w-5 h-5 text-amber-500"/></div></Card><Card><div className="flex justify-between"><div><div className="text-xs uppercase tracking-wider font-semibold text-slate-500">Hoàn tất</div><div className="mt-2 text-3xl font-bold text-slate-950">{completed}</div></div><PackageCheck className="w-5 h-5 text-emerald-600"/></div></Card><Card><div className="flex justify-between"><div><div className="text-xs uppercase tracking-wider font-semibold text-slate-500">Khối lượng theo dữ liệu hiện có</div><div className="mt-2 text-3xl font-bold text-slate-950">{kg.toFixed(1)} <span className="text-sm font-medium text-slate-500">kg</span></div></div><Recycle className="w-5 h-5 text-emerald-600"/></div></Card></div>
 <div className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-sm"><div className="px-5 py-4 border-b border-slate-100 flex items-center justify-between gap-4"><div><div className="font-semibold text-slate-900">Danh sách pickup</div><div className="text-xs text-slate-500 mt-1">{filtered.length} bản ghi</div></div><div className="relative w-72 max-w-full"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} className="field-control pl-9" placeholder="Tìm khách hàng, địa chỉ..."/></div></div>{loading?<div className="p-14 text-center text-sm text-slate-500">Đang tải...</div>:error?<div className="p-10 text-center text-red-700">{error}</div>:filtered.length===0?<div className="p-14 text-center text-sm text-slate-500">Chưa có yêu cầu thu gom.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500 border-b border-slate-200"><tr><th className="px-5 py-3 text-left">Khách hàng</th><th className="px-5 py-3 text-left">Địa chỉ</th><th className="px-5 py-3 text-left">Bao bì</th><th className="px-5 py-3 text-left">Khối lượng</th><th className="px-5 py-3 text-left">Ngày hẹn</th><th className="px-5 py-3 text-left">Trạng thái</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(p=><tr key={p.id} className="hover:bg-slate-50"><td className="px-5 py-4"><div className="font-medium text-slate-900">{p.profiles?.name||'Khách hàng'}</div><div className="text-xs text-slate-400">{p.profiles?.phone||'SĐT được bảo vệ'}</div></td><td className="px-5 py-4 text-slate-600 max-w-sm"><div className="line-clamp-2">{p.address}</div></td><td className="px-5 py-4 font-medium text-slate-800">{p.packaging_type}</td><td className="px-5 py-4 font-mono text-xs text-slate-700">{Number(p.verified_quantity_kg??p.estimated_quantity_kg).toFixed(1)} kg</td><td className="px-5 py-4 text-slate-600 whitespace-nowrap">{new Date(p.pickup_date+'T00:00:00').toLocaleDateString('vi-VN')}</td><td className="px-5 py-4"><StatusPill status={p.status}/></td></tr>)}</tbody></table></div>}</div></div>
}
