"use client";
import { useCallback, useEffect, useState } from "react";
import { Award, ArrowUpRight, ArrowDownLeft, RefreshCw, TrendingUp } from "lucide-react";

type Tx={id:string;points_delta:number;description:string;created_at:string;transaction_type:string};
export default function CustomerPointsPage(){const [total,setTotal]=useState(0);const[txs,setTxs]=useState<Tx[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/customer/points');const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error?.message||'Không tải được Green Points');setTotal(j.data.total_points||0);setTxs(j.data.transactions||[])}catch(e){setError(e instanceof Error?e.message:'Không tải được Green Points')}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);const earned=txs.filter(t=>t.points_delta>0).reduce((s,t)=>s+t.points_delta,0);const spent=Math.abs(txs.filter(t=>t.points_delta<0).reduce((s,t)=>s+t.points_delta,0));return <div className="space-y-6">
<div className="flex items-start justify-between pb-6 border-b border-slate-200"><div><div className="text-xs uppercase tracking-wider font-semibold text-emerald-600">Green Points Ledger</div><h1 className="mt-2 text-2xl font-bold text-slate-900">Sổ điểm Green Points</h1><p className="mt-1 text-sm text-slate-500">Số dư được tính trực tiếp từ ledger giao dịch, không lưu số dư giả.</p></div><button onClick={load} className="p-2 rounded-lg border border-slate-200 bg-white text-slate-500"><RefreshCw className="w-4 h-4"/></button></div>
{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
<div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Stat icon={<Award/>} label="Số dư hiện tại" value={loading?'—':total.toLocaleString('vi-VN')} suffix="pts"/><Stat icon={<TrendingUp/>} label="Đã tích lũy" value={earned.toLocaleString('vi-VN')} suffix="pts"/><Stat icon={<ArrowDownLeft/>} label="Đã sử dụng" value={spent.toLocaleString('vi-VN')} suffix="pts"/></div>
<div className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-sm"><div className="px-5 py-4 border-b border-slate-100"><h2 className="font-semibold text-slate-900">Giao dịch điểm</h2></div>{loading?<div className="p-10 text-center text-sm text-slate-500">Đang tải...</div>:txs.length===0?<div className="p-12 text-center text-sm text-slate-500">Chưa có giao dịch điểm thưởng.</div>:txs.map(t=>{const pos=t.points_delta>0;return <div key={t.id} className="px-5 py-4 flex items-center gap-4 border-b last:border-b-0 border-slate-100 hover:bg-slate-50"><div className={`w-9 h-9 rounded-xl flex items-center justify-center ${pos?'bg-emerald-50 text-emerald-600':'bg-red-50 text-red-600'}`}>{pos?<ArrowUpRight className="w-4 h-4"/>:<ArrowDownLeft className="w-4 h-4"/>}</div><div className="flex-1 min-w-0"><div className="text-sm font-medium text-slate-900">{t.description}</div><div className="mt-1 text-xs text-slate-400">{new Date(t.created_at).toLocaleString('vi-VN')}</div></div><div className={`font-semibold ${pos?'text-emerald-600':'text-red-600'}`}>{pos?'+':''}{t.points_delta} pts</div></div>})}</div></div>}
function Stat({icon,label,value,suffix}:{icon:React.ReactNode;label:string;value:string|number;suffix:string}){return <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm flex items-start justify-between"><div><div className="text-xs font-medium text-slate-500">{label}</div><div className="mt-2 text-3xl font-bold text-slate-900">{value} <span className="text-sm font-medium text-slate-400">{suffix}</span></div></div><div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center [&>svg]:w-5 [&>svg]:h-5">{icon}</div></div>}
