"use client";
import { useCallback, useEffect, useState } from "react";
import QRCode from "qrcode";
import { Ticket, QrCode, RefreshCw, Loader2, CheckCircle2 } from "lucide-react";

type Voucher={id:string;name:string;description:string|null;points_required:number;discount_type:string;discount_value:number;quantity:number;expiry_date:string};
type Redemption={id:string;voucher_id:string;points_spent:number;redemption_code:string;status:string;qr_expires_at:string|null;redeemed_at:string;used_at:string|null;vouchers:{id:string;name:string;description:string|null;discount_type:string;discount_value:number;expiry_date:string}|null};

export default function CustomerVouchersPage(){
 const [tab,setTab]=useState<'catalog'|'mine'>('catalog');const[balance,setBalance]=useState(0);const[catalog,setCatalog]=useState<Voucher[]>([]);const[mine,setMine]=useState<Redemption[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState('');const[qr,setQr]=useState<{url:string;code:string;expires:string}|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/customer/vouchers');const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error?.message||'Không tải được voucher');setBalance(j.data.balance||0);setCatalog(j.data.catalog||[]);setMine(j.data.redemptions||[])}catch(e){setError(e instanceof Error?e.message:'Không tải được voucher')}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 const redeem=async(id:string)=>{setBusy(id);setError('');try{const r=await fetch('/api/vouchers/redeem',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({voucher_id:id})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error?.message||'Không đổi được voucher');await load();setTab('mine')}catch(e){setError(e instanceof Error?e.message:'Không đổi được voucher')}finally{setBusy(null)}};
 const showQr=async(redemption:Redemption)=>{setBusy(redemption.id);setError('');try{const r=await fetch(`/api/vouchers/${redemption.id}/qr`,{method:'POST'});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error?.message||'Không tạo được QR');const payload=JSON.stringify({type:'greenbridge_voucher',redemption_id:redemption.id,token:j.data.qrToken});const url=await QRCode.toDataURL(payload,{width:320,margin:2});setQr({url,code:j.data.redemption_code,expires:j.data.qr_expires_at})}catch(e){setError(e instanceof Error?e.message:'Không tạo được QR')}finally{setBusy(null)}};
 return <div className="space-y-6">
  <div className="flex items-start justify-between pb-6 border-b border-slate-200"><div><div className="text-xs uppercase tracking-wider font-semibold text-emerald-600">Rewards</div><h1 className="mt-2 text-2xl font-bold text-slate-900">Voucher GreenBridge</h1><p className="mt-1 text-sm text-slate-500">Đổi Green Points bằng RPC atomic và quản lý QR single-use của bạn.</p></div><button onClick={load} className="p-2 rounded-lg border border-slate-200 bg-white text-slate-500"><RefreshCw className="w-4 h-4"/></button></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <div className="bg-white border border-slate-200 rounded-xl p-1 inline-flex gap-1"><button onClick={()=>setTab('catalog')} className={`px-4 py-2 rounded-lg text-sm font-semibold ${tab==='catalog'?'bg-emerald-50 text-emerald-700':'text-slate-500 hover:bg-slate-50'}`}>Đổi voucher · {balance} pts</button><button onClick={()=>setTab('mine')} className={`px-4 py-2 rounded-lg text-sm font-semibold ${tab==='mine'?'bg-emerald-50 text-emerald-700':'text-slate-500 hover:bg-slate-50'}`}>Voucher của tôi · {mine.length}</button></div>
  {loading?<div className="p-12 text-center text-sm text-slate-500">Đang tải voucher...</div>:tab==='catalog'?<div className="grid grid-cols-1 xl:grid-cols-2 gap-4">{catalog.length===0?<Empty/>:catalog.map(v=><div key={v.id} className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm"><div className="flex gap-4"><div className="w-11 h-11 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center"><Ticket className="w-5 h-5"/></div><div className="flex-1"><div className="font-semibold text-slate-900">{v.name}</div><p className="mt-1 text-sm text-slate-500">{v.description}</p></div></div><div className="mt-5 pt-4 border-t border-slate-100 flex items-center justify-between"><div><div className="text-xs text-slate-400">Chi phí</div><div className="font-semibold text-emerald-700">{v.points_required} Green Points</div></div><button disabled={busy===v.id||balance<v.points_required} onClick={()=>redeem(v.id)} className="px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-semibold disabled:opacity-40">{busy===v.id?<Loader2 className="w-4 h-4 animate-spin"/>:'Đổi ngay'}</button></div></div>)}</div>:<div className="grid grid-cols-1 xl:grid-cols-2 gap-4">{mine.length===0?<Empty/>:mine.map(r=><div key={r.id} className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm"><div className="flex justify-between gap-4"><div><div className="font-semibold text-slate-900">{r.vouchers?.name||'Voucher GreenBridge'}</div><div className="mt-1 text-xs text-slate-500">Mã đổi thưởng: <span className="font-mono">{r.redemption_code}</span></div></div><span className={`h-fit px-2.5 py-1 rounded-full text-xs font-semibold ${r.status==='active'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{r.status}</span></div><div className="mt-5 pt-4 border-t border-slate-100 flex items-center justify-between"><div className="text-xs text-slate-500">Đã dùng {r.points_spent} pts · {new Date(r.redeemed_at).toLocaleDateString('vi-VN')}</div>{r.status==='active'&&<button onClick={()=>showQr(r)} disabled={busy===r.id} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-emerald-200 bg-emerald-50 text-emerald-700 text-sm font-semibold"><QrCode className="w-4 h-4"/> Hiện QR</button>}</div></div>)}</div>}
  {qr&&<div className="fixed inset-0 bg-slate-950/40 backdrop-blur-sm z-50 flex items-center justify-center p-4"><div className="w-full max-w-sm bg-white rounded-2xl border border-slate-200 shadow-2xl p-6 text-center"><CheckCircle2 className="w-8 h-8 text-emerald-600 mx-auto"/><h2 className="mt-3 font-bold text-slate-900">QR voucher đang hoạt động</h2><img src={qr.url} alt="QR voucher" className="w-64 h-64 mx-auto mt-4 rounded-xl border border-slate-100"/><div className="mt-3 font-mono text-xs text-slate-500 break-all">{qr.code}</div><div className="mt-2 text-xs text-slate-400">Hết hạn: {new Date(qr.expires).toLocaleString('vi-VN')}</div><button onClick={()=>setQr(null)} className="mt-5 w-full py-2.5 rounded-lg bg-slate-900 text-white text-sm font-semibold">Đóng</button></div></div>}
 </div>
}
function Empty(){return <div className="col-span-full bg-white border border-dashed border-slate-300 rounded-2xl p-12 text-center"><Ticket className="w-8 h-8 text-slate-300 mx-auto"/><div className="mt-3 font-semibold text-slate-800">Chưa có voucher</div><p className="mt-1 text-sm text-slate-500">Khi có ưu đãi hoặc voucher đã đổi, chúng sẽ xuất hiện tại đây.</p></div>}
