"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowRight, Leaf, Lock, Mail, Phone, User, ShieldAlert, Loader2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function RegisterPage(){const router=useRouter();const[name,setName]=useState('');const[email,setEmail]=useState('');const[phone,setPhone]=useState('');const[password,setPassword]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{const supabase=createClient();const{data,error}=await supabase.auth.signUp({email,password,options:{data:{name,phone,account_type:'customer'}}});if(error)throw error;if(data.user)router.push('/customer/home')}catch(err){setError(err instanceof Error?err.message:'Không thể đăng ký')}finally{setLoading(false)}};return <div className="min-h-screen bg-slate-50 grid grid-cols-1 lg:grid-cols-2">
<div className="hidden lg:flex p-12 xl:p-20 bg-white border-r border-slate-200 flex-col justify-between"><Link href="/" className="flex items-center gap-3"><div className="w-9 h-9 rounded-xl bg-emerald-600 text-white flex items-center justify-center"><Leaf className="w-5 h-5"/></div><span className="font-bold">GreenBridge AI</span></Link><div><div className="text-xs uppercase tracking-wider font-semibold text-emerald-600">Customer Portal</div><h1 className="mt-4 text-4xl font-bold leading-tight max-w-xl">Hoàn trả bao bì, theo dõi tác động và nhận Green Points minh bạch.</h1><p className="mt-4 text-slate-500 leading-7 max-w-lg">Tài khoản đăng ký công khai luôn được tạo với quyền customer. Quyền vận hành shop được cấp riêng bởi admin.</p></div><div className="text-xs text-slate-400">Supabase Auth · RLS · Green Points Ledger</div></div>
<div className="flex items-center justify-center p-6 lg:p-12"><div className="w-full max-w-md"><div className="lg:hidden flex items-center gap-3 mb-8"><div className="w-9 h-9 rounded-xl bg-emerald-600 text-white flex items-center justify-center"><Leaf className="w-5 h-5"/></div><span className="font-bold">GreenBridge AI</span></div><div className="bg-white border border-slate-200 rounded-2xl p-7 shadow-sm"><h2 className="text-2xl font-bold text-slate-900">Đăng ký khách hàng</h2><p className="mt-1 text-sm text-slate-500">Tạo tài khoản để sử dụng reverse logistics và Green Points.</p>{error&&<div className="mt-5 p-3 rounded-xl border border-red-200 bg-red-50 text-red-700 text-sm flex gap-2"><ShieldAlert className="w-4 h-4 mt-0.5"/>{error}</div>}<form onSubmit={submit} className="mt-6 space-y-4"><Field icon={<User/>} label="Họ và tên"><input className="field-control pl-10" value={name} onChange={e=>setName(e.target.value)} required placeholder="Nguyễn Văn A"/></Field><Field icon={<Phone/>} label="Số điện thoại"><input className="field-control pl-10" value={phone} onChange={e=>setPhone(e.target.value)} required placeholder="0912345678"/></Field><Field icon={<Mail/>} label="Email"><input type="email" className="field-control pl-10" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></Field><Field icon={<Lock/>} label="Mật khẩu"><input type="password" minLength={6} className="field-control pl-10" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="Tối thiểu 6 ký tự"/></Field><button disabled={loading} className="w-full h-11 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white font-semibold text-sm flex items-center justify-center gap-2 disabled:opacity-50">{loading?<Loader2 className="w-4 h-4 animate-spin"/>:<>Tạo tài khoản <ArrowRight className="w-4 h-4"/></>}</button></form><div className="mt-5 text-center text-sm text-slate-500">Đã có tài khoản? <Link href="/login" className="font-semibold text-emerald-700">Đăng nhập</Link></div></div></div></div></div>}
function Field({icon,label,children}:{icon:React.ReactNode;label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-semibold text-slate-700">{label}</span><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 [&>svg]:w-4 [&>svg]:h-4">{icon}</span>{children}</div></label>}
